[package]
name = "charpaper"
version.workspace = true
edition.workspace = true

[dependencies]
charpaper-scene.workspace = true
charpaper-wallpaper.workspace = true

anyhow.workspace = true
bevy.workspace = true
clap.workspace = true

[target.'cfg(windows)'.dependencies]
charpaper-windows.workspace = true
